version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
